### ISSUE TITLE
Update peer dependencies to include React 18

### ISSUE THREAD

**Issue by RinMinase** [eugenezinovyev/react-fontawesome-svg-icon#18]
Thank you for this library, as this managed to shave off a lot of the final bundle size. 😁

**Describe the bug**
This library when installed via NPM with version 1.1.1, it still requires React 17 for its peer dependencies.

<img width="318" alt="image" src="https://user-images.githubusercontent.com/7098304/188606353-a5cc9325-4e52-4a69-827c-4bcc2e01bbf2.png">

[React 18](https://reactjs.org/blog/2022/03/29/react-v18.html) was also out last April 2022.

**To Reproduce**
1. Generate a new project with `yarn init --yes`
2. Install the packages required `yarn add react react-fontawesome-svg-icon`
3. See warnings presented

<img width="665" alt="image" src="https://user-images.githubusercontent.com/7098304/188607822-405af8c8-0fd3-42ab-9b43-bbff3d8120f7.png">

This happens because the installed version of react is 18 (latest as of this writing), but your svg library [depends on react 17](https://github.com/eugenezinovyev/react-fontawesome-svg-icon/blob/13ba1861fe2129757b7bd8bd7fc18ce3e4b284c3/packages/react-fontawesome-svg-icon/package.json#L25).

**Expected behavior**
There should be no warnings presented.

**Desktop (please complete the following information):**
 - OS: both happens on Windows 10 & MacOS 12
 - Browser: None (this happens on the shell-level)
 - Package Manager: [Yarn](https://www.google.com/search?client=safari&rls=en&q=yarnpkg&ie=UTF-8&oe=UTF-8)
 - Version: 1.1.1

**Comment by eugenezinovyev** [comment]
Glad to hear this library is helpful!
It works with React 18 with no issues as per my research despite the warning.
However, I've updated peer dependencies in [v1.1.2](https://www.npmjs.com/package/react-fontawesome-svg-icon/v/1.1.2)

Let me know if you have anything else, thanks.
